name = "OkReadGSheet"
uuid = "760a1398-8f00-4da5-9475-268514cb6295"
authors = ["okatsn <okatsn@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.9"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
